FROM amazoncorretto:18-alpine3.15

LABEL maintainer="reader@lucaskjaerozhang.com"
WORKDIR /app
ENV INSTALL_DIR /usr/local
ENV SBT_HOME /usr/local/sbt
ENV PATH ${PATH}:${SBT_HOME}/bin

# Keep failing pipe command from reporting success to the build.
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# Sbt requires bash for some reason
RUN apk add --no-cache bash=5.1.16-r0

ENV SBT_VERSION 1.7.0

# Install sbt
RUN mkdir -p "$SBT_HOME" && \
    apk add --no-cache wget=1.21.2-r2 && \
    wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" |  tar xz -C $INSTALL_DIR && \
    echo "- with sbt $SBT_VERSION" >> /root/.built && \
    apk del wget 
# wget just exists to install sbt