FROM python:3.10-alpine3.16

LABEL maintainer="reader@lucaskjaerozhang.com"
WORKDIR /app
ENV INSTALL_DIR /usr/local
ENV S3CMD_DIR $INSTALL_DIR/s3cmd-2.2.0
ENV PATH="$S3CMD_DIR:${PATH}"

# Keep failing pipe command from reporting success to the build.
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# Install wget to download dictionaries and full tar to open them
RUN apk add --no-cache wget=1.21.3-r0 tar=1.34-r0

# Install s3cmd
RUN wget -qO - --no-check-certificate "https://github.com/s3tools/s3cmd/releases/download/v2.2.0/s3cmd-2.2.0.tar.gz" |  tar xz -C $INSTALL_DIR && \
  cd $S3CMD_DIR && \
  python setup.py install
