apiVersion: v1
kind: Pod
metadata:
  namespace: content
spec:
  imagePullSecrets:
  - 'dockerhub'
  containers:
  - name: s3
    image: lkjaero/jenkins-runners:s3
    command:
    - sleep
    args:
    - 99d
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: do-spaces-access-key
          key: username
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: do-spaces-access-key
          key: password