name: Build jenkins worker containers
on:
  pull_request:
    types: [closed]

  s3-container:
    name: Make a container with an s3 client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build container
      run: |
        docker build -f Dockerfile_s3 . -t lkjaero/jenkins-runners:s3
        docker push lkjaero/jenkins-runners:s3